apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  selector:
    app: whoami
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30010
      port: 80
      targetPort: 8080