version: "3"

services:

  app:
    container_name: whoami
    image: "spring-practice/whoami:latest"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        JAR: "target/whoami-1.0.jar"
    user: cloudy
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    command: ["java", "-jar", "whoami.jar"]